# Generated by Django 4.2.10 on 2025-05-26 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0007_course_coursetype_employee_student_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_no', models.CharField(blank=True, max_length=10, null=True)),
                ('admission_no', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('caste', models.CharField(max_length=50)),
                ('student_phone_no', models.CharField(max_length=15)),
                ('parent_phone_no', models.CharField(max_length=15)),
                ('pu_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pu_reg_no', models.CharField(max_length=30)),
                ('year_of_passing', models.PositiveIntegerField()),
                ('dob', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('quota_type', models.CharField(choices=[('Regular', 'Regular'), ('Management', 'Management')], default='Regular', max_length=20)),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Shortlisted Management', 'Shortlisted for Management')], default='Pending', max_length=30)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_admissions', to='master.course')),
                ('course_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_admissions', to='master.coursetype')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeAdmissionshortlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('quota_type', models.CharField(choices=[('Regular', 'Regular'), ('Management', 'Management')], max_length=20)),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Shortlisted(M)', 'Shortlisted Management')], default='Pending', max_length=50)),
                ('admin_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PUAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_no', models.CharField(blank=True, max_length=10, null=True)),
                ('admission_no', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_mobile_no', models.CharField(max_length=15)),
                ('aadhar_no', models.CharField(max_length=12)),
                ('caste', models.CharField(max_length=50)),
                ('sslc_reg_no', models.CharField(max_length=30)),
                ('sslc_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/photos/')),
                ('year_of_passing', models.PositiveIntegerField(blank=True, null=True)),
                ('quota_type', models.CharField(choices=[('Regular', 'Regular'), ('Management', 'Management')], default='Regular', max_length=20)),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Shortlisted Management', 'Shortlisted for Management')], default='Pending', max_length=30)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pu_admissions', to='master.course')),
                ('course_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pu_admissions', to='master.coursetype')),
            ],
        ),
        migrations.CreateModel(
            name='PUAdmissionshortlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('quota_type', models.CharField(choices=[('Regular', 'Regular'), ('Management', 'Management')], max_length=20)),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Shortlisted(M)', 'Shortlisted Management')], default='Pending', max_length=50)),
                ('admin_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PUFeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scholarship', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_mode', models.CharField(choices=[('Full', 'Full Payment'), ('Installment', 'Installment')], max_length=20)),
                ('due_date_1', models.DateField(blank=True, null=True)),
                ('due_date_2', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.puadmission')),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_no', models.CharField(max_length=10, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=15)),
                ('percentage_10th', models.FloatField()),
                ('percentage_12th', models.FloatField(blank=True, null=True)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='master.course')),
                ('course_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='master.coursetype')),
            ],
        ),
        migrations.CreateModel(
            name='DegreeFeeDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scholarship', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('emi_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_mode', models.CharField(choices=[('Full', 'Full Payment'), ('Installment', 'Installment')], max_length=20)),
                ('due_date_1', models.DateField(blank=True, null=True)),
                ('due_date_2', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admission.degreeadmission')),
            ],
        ),
    ]
