# Generated by Django 4.2.20 on 2025-10-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeecollection',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.feemaster'),
        ),
        migrations.AddField(
            model_name='puadmission',
            name='admitted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pu_admitted_students', to='master.course'),
        ),
        migrations.AddField(
            model_name='puadmission',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pu_admissions', to='master.course'),
        ),
        migrations.AddField(
            model_name='puadmission',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pu_admissions', to='master.coursetype'),
        ),
        migrations.AddField(
            model_name='puadmission',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.transport'),
        ),
        migrations.AddField(
            model_name='followup',
            name='degree_enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.enquiry2'),
        ),
        migrations.AddField(
            model_name='followup',
            name='pu_enquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admission.enquiry1'),
        ),
        migrations.AddField(
            model_name='enquiry2',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.course'),
        ),
        migrations.AddField(
            model_name='enquiry2',
            name='course_type',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.PROTECT, to='master.coursetype'),
        ),
        migrations.AddField(
            model_name='enquiry1',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.course'),
        ),
        migrations.AddField(
            model_name='enquiry1',
            name='course_type',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.PROTECT, to='master.coursetype'),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='admitted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_students', to='master.course'),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_admissions', to='master.course'),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='course_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degree_admissions', to='master.coursetype'),
        ),
        migrations.AddField(
            model_name='degreeadmission',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.transport'),
        ),
        migrations.AddField(
            model_name='confirmedadmission',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.academicyear'),
        ),
        migrations.AddField(
            model_name='confirmedadmission',
            name='degree_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_degree_admissions', to='admission.degreeadmission'),
        ),
        migrations.AddField(
            model_name='confirmedadmission',
            name='pu_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_pu_admissions', to='admission.puadmission'),
        ),
    ]
