# Generated by Django 4.2.20 on 2025-10-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('current_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.course')),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.coursetype')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('student_userid', models.CharField(blank=True, max_length=50, null=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Bank Transfer', 'Bank Transfer')], max_length=30, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('applied_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receipt_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('receipt_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.feetype')),
            ],
        ),
        migrations.CreateModel(
            name='OptionalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('admission_no', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.feetype')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.studentdatabase')),
            ],
        ),
        migrations.CreateModel(
            name='FeeDeclarationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_details', to='fees.feedeclaration')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.feetype')),
            ],
        ),
    ]
