# Generated by Django 4.2.20 on 2025-10-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
                ('holiday_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_working_day', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CL', 'Casual Leave'), ('SL', 'Sick Leave / Medical Leave'), ('EL', 'Earned Leave / Privilege Leave'), ('LOP', 'Loss of Pay / Unpaid Leave'), ('ML', 'Maternity Leave'), ('PL', 'Paternity Leave'), ('BL', 'Bereavement / Compassionate Leave'), ('Marriage', 'Marriage Leave'), ('Sabbatical', 'Sabbatical / Study Leave'), ('Optional', 'Optional / Privilege Holiday'), ('CO', 'Compensatory Off / Comp Off'), ('Volunteer', 'Volunteer / CSR Leave'), ('WFH', 'Work From Home Days'), ('Adoption', 'Adoption Leave'), ('Special', 'Special Leave / Festival Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('admin_reason', models.TextField(blank=True, null=True)),
                ('leave_days', models.PositiveIntegerField(default=0)),
                ('next_working_day', models.DateField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('is_approved', models.BooleanField(blank=True, default=None, null=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.employee')),
            ],
            options={
                'db_table': 'hr_leave',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_code', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('special_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lwf_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pf_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gross_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_declarations', to='master.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalarySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_days', models.IntegerField(default=0)),
                ('present_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('lop_days', models.IntegerField(default=0)),
                ('salary_deduction', models.FloatField(default=0)),
                ('final_salary', models.FloatField(default=0)),
                ('net_pay_in_words', models.CharField(blank=True, max_length=255, null=True)),
                ('emp_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('uan_number', models.CharField(blank=True, max_length=12, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('pf_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pension_no', models.CharField(blank=True, max_length=50, null=True)),
                ('esi_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
