# Generated by Django 4.2.20 on 2025-10-17 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=9, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration_years', models.PositiveIntegerField()),
                ('total_semesters', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('is_deductible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=9)),
                ('promotion_cycle', models.CharField(max_length=9)),
                ('from_year', models.IntegerField(blank=True, null=True)),
                ('to_year', models.IntegerField(blank=True, null=True)),
                ('from_semester', models.IntegerField(blank=True, null=True)),
                ('to_semester', models.IntegerField(blank=True, null=True)),
                ('promotion_date', models.DateField(blank=True, null=True)),
                ('student_userid', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'student_promotion_history',
            },
        ),
        migrations.CreateModel(
            name='SentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('send_sms', models.BooleanField(default=False)),
                ('send_whatsapp', models.BooleanField(default=False)),
                ('department', models.CharField(max_length=100)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admission_no', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('course_type', models.CharField(choices=[('PU', 'PU'), ('Degree', 'Degree')], max_length=10)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('quota_type', models.CharField(max_length=20)),
                ('admission_date', models.DateField()),
            ],
            options={
                'db_table': 'master_student',
            },
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('guardian_relation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=255)),
                ('bus_no', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_contact_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='UserCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('passcode', models.CharField(blank=True, max_length=10, null=True)),
                ('passcode_set', models.BooleanField(default=False)),
                ('can_reset_password', models.BooleanField(default=False)),
                ('wrong_attempts', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(blank=True, max_length=20, null=True)),
                ('credit', models.PositiveIntegerField(blank=True, null=True)),
                ('semester', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.academicyear')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.course')),
                ('program_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.coursetype')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('quota_type', models.CharField(blank=True, max_length=20, null=True)),
                ('student_userid', models.CharField(blank=True, max_length=50, null=True)),
                ('student_phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('current_year', models.IntegerField(blank=True, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Graduated', 'Graduated'), ('Dropped', 'Dropped'), ('Transferred', 'Transferred'), ('Suspended', 'Suspended'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_database', to='master.course')),
                ('course_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_database_entries', to='master.coursetype')),
                ('degree_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_degree_admissions', to='admission.degreeadmission')),
                ('pu_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_pu_admissions', to='admission.puadmission')),
            ],
            options={
                'db_table': 'master_student_database',
            },
        ),
        migrations.CreateModel(
            name='SentMessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('sent_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='master.sentmessage')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.course')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(max_length=100)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.academicyear')),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.course')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.coursetype')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_userid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('employee_password', models.CharField(blank=True, max_length=50, null=True)),
                ('password_changed', models.BooleanField(default=False)),
                ('passcode', models.CharField(blank=True, max_length=10, null=True)),
                ('passcode_set', models.BooleanField(default=False)),
                ('wrong_attempts', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('role', models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=20, null=True)),
                ('category', models.CharField(choices=[('Teaching Staff', 'Teaching Staff'), ('Non-Teaching Staff', 'Non-Teaching Staff')], max_length=30)),
                ('emp_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant', 'Assistant')], max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time')], max_length=20)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('uan_number', models.CharField(blank=True, max_length=12, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('pf_number', models.CharField(blank=True, max_length=50, null=True)),
                ('esi_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.usercustom')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='master.coursetype'),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('PDF', 'PDF'), ('Video', 'Video'), ('Text', 'Text'), ('Assignment', 'Assignment'), ('Link', 'Link')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='lms_content/')),
                ('text', models.TextField(blank=True, null=True)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='master.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='master.subject'),
        ),
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=150)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_access', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.usercustom')),
            ],
            options={
                'unique_together': {('user', 'form_name')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeSubjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='master.employee')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.subject')),
            ],
            options={
                'unique_together': {('employee', 'course', 'semester', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='CollegeStartEndPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('semester_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.course')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.coursetype')),
            ],
            options={
                'unique_together': {('program_type', 'academic_year', 'course', 'semester_number')},
            },
        ),
    ]
