# Generated by Django 4.2.10 on 2025-05-26 11:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0007_course_coursetype_employee_student_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_extra', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10)),
                ('marked_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.period')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.student')),
            ],
            options={
                'unique_together': {('student', 'period', 'date')},
            },
        ),
    ]
