# Generated by Django 4.2.20 on 2025-10-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTrackingLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'driver_tracking_location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=15)),
                ('route_name', models.CharField(max_length=100)),
                ('total_seats', models.IntegerField()),
                ('available_seats', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'master_transport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StopArrivalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reached_at', models.DateTimeField(auto_now_add=True)),
                ('message_sent', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'stop_arrival_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentTransportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year_id', models.IntegerField()),
                ('transport_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assigned_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_transport_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransportFeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year_id', models.IntegerField()),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'transport_fee_structure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=100)),
                ('total_stops', models.IntegerField()),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estimated_time', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transport_route',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransportStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('stop_order', models.IntegerField()),
                ('pickup_time', models.TimeField()),
                ('drop_time', models.TimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'db_table': 'transport_stop',
                'managed': False,
            },
        ),
    ]
